export const CREATE_TODO_LIST = 'CREATE_TODO_LIST';
export const DELETE_TODO_LIST = 'DELETE_TODO_LIST';
export const GET_TODO_LIST = 'GET_TODO_LIST';
export const LOADING_TODO_LIST = 'LOADING_TODO_LIST';
export const LOADED_TODO_LIST = 'LOADED_TODO_LIST';
export const ERROR_GET_TODO_LIST = 'ERROR_GET_TODO_LIST';

export const CREATE_TODO_ITEM = 'CREATE_TODO_ITEM';
export const TOGGLE_TODO_ITEM = 'TOGGLE_TODO_ITEM';
export const DELETE_TODO_ITEM = 'DELETE_TODO_ITEM';

